### ISSUE TITLE
Add players Leaderboard table

### ISSUE THREAD

**Issue by captainWaheed** [captainWaheed/DCA-Scores#1]

**Comment by captainWaheed** [comment]
# Description

## Todo
- [ ] Make the section and divide it.
- [ ] Apply the map function to reflect all the data in the table
- [ ] Apply necessary stylings according to the theme.

**Comment by captainWaheed** [comment]
Issue resolved!
